select * from ITEM;

INSERT INTO ITEM(ITEM_CODE, BUSINESS_CODE, CLASSIFY_CODE, ITEM_NAME, ITEM_PRICE, ITEM_DESCRIPTION, ITEM_STATE, ITEM_RECOMMENDATION, ITEM_UPDATE_DATE, DELIVERY_PRICE, ITEM_SIZE, ITEM_WEIGHT, ITEM_MATERIAL, ITEM_STAR, ITEM_ENTRANCE_TIME, ITEM_LEAVING_TIME)
VALUES ('itemcode1', 563821562, 'ITL', 'itemName1', 5000, 'item1의 설명', 'N', 5, '', 2000, '1.2m', '0.5kg', '재질', 4, '','');

commit;
